server:
  port: 8083

spring:

  data:
    mongodb:
      uri: "mongodb+srv://abhishekmali7710_db_user:mummy123abhi@abhi01cluster.zbdjysk.mongodb.net/fitnessrecommendation?retryWrites=true&w=majority"
      database: fitnessrecommendation

    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

gemini:
  api:
    url: ${GEMINI_API_URL:https://openrouter.ai/api/v1/chat/completions}
    key: ${GEMINI_API_KEY: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}
    model: ${GEMINI_API_MODEL:google/gemma-3n-e2b-it:free}